### ISSUE TITLE
Should we consistently use MyST-Markdown?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#10]
Some pages are written in ReStructuredText, while most of the pages are in MyST-Markdown. We could convert everything to MyST, but in some cases the indentation based RST seems to result in a more readable source file.

Any opinions?

**Comment by certik** [comment]
My understanding is that MyST is equivalent to RST? Can you show an example where RST does something that we currently do not know how to do in MyST? Let me have a look.

**Comment by awvwgk** [comment]
I'm mostly worried about the MyST syntax becoming unreadable for deeply nested cases like in

https://github.com/fortran-lang/webpage/blob/f9f8789278d794cf776b36825b0eaef8ec49b914/source/learn.rst#L22-L39

Otherwise we should be able to do everything in MyST.

**Comment by henilp105** [comment]
Sir, we won't be able to render the data as rendering via sphinx jinja works only works in rst ( through ` .. jinja: ` directive ) and not in md files. those variables are not accessible in md files .

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk @certik

**Comment by certik** [comment]
@awvwgk how would the example you posted in RST look in MyST?

**Comment by certik** [comment]
The Jinja rendering that @henilp105 mentioned is for example:
```rst
.. jinja:: conf

    {% for j in categories %}
    .. div:: sd-fs-4 sd-font-weight-bold sd-text-primary

        {{j.name}}

    .. grid:: 2
    {% for b in books %}
    {% if b.category == j.name %}

        .. grid-item-card::
            :columns: 6
            :shadow: none

            .. div:: sd-fs-5 sd-font-weight-bold sd-text-primary

                :octicon:`book;1em;sd-text-info` `{{b.title}} <{{"../"+b.link[1:]+"/"}}>`_
            {{b.description}}
    {% endif %}
    {% endfor %}
    {% endfor %}
```

So we would need to figure out a solution for that as well.

**Comment by awvwgk** [comment]
Checkout #22 for porting the whole learn page to MyST. The *jinja* directive seems to work without issues in MyST.

**Comment by henilp105** [comment]
yes sir. I will port them soon.

**Comment by henilp105** [comment]
PR #24 resolves this. thus, I request this issue to be closed.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
