### ISSUE TITLE
Using a translation service

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#11]
Should we try to adopt a translation service like [transifex](https://www.transifex.com/) or [weblate](https://weblate.org/)?

I tried weblate for submitted translations and the web interface works quite well. Sign-in works with just a GitHub account.

**Comment by 14NGiestas** [comment]
Such services are great for people that just want to help with translations, it lowers the barrier for contributors that may be able to help but can't figure out the git flow. Also, there's the advantage of building a glossary of common terms in each language so the translations get consistent.

https://docs.weblate.org/en/latest/devel/integration.html

**Comment by awvwgk** [comment]
I would start with signing in https://github.com/fortran-lang/fpm-docs for weblate to see whether we can get approved for a free instance.

cc @fortran-lang/admins

**Comment by awvwgk** [comment]
I started to setup a project for the fpm-docs and the new webpage at https://hosted.weblate.org/projects/fortran-lang/

**Comment by awvwgk** [comment]
We got approved now for free hosting for our open source project.
