### ISSUE TITLE
Reduce diff between sphinx-intl and weblate modified po-files

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#116]
Updating the po-files with the `sphinx-intl` results in a huge diff due to changes in the maximum line length. We should investigate whether there is an option to get this consistent between weblate and sphinx-intl to avoid generating useless diffs.

**Comment by henilp105** [comment]
@awvwgk  We would be able to set specific line length using black , what should be the apt line length ? ( black default is 88).

Thanks and Reagrds,
Henil Shalin Panchal

**Comment by awvwgk** [comment]
Found the `-w` option for `sphinx-intl`, we should find a length which minimizes the change in the po-files.

```
❯ sphinx-intl update --help
Usage: sphinx-intl update [OPTIONS]
...
Options:
...
  -w, --line-width <WIDTH>  The maximum line width for the po files, 0 or a
                            negative number disable line wrapping  [default:
                            76]
```

**Comment by henilp105** [comment]
Thanks Sir, Will find most apt -w for po-files.
