### ISSUE TITLE
Broken format in intrinsics

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#118]
Looks like we need to escape the exponential operator `**` as `\*\*` or use backticks ``` ` ``` here.

![image](https://user-images.githubusercontent.com/28669218/185741789-2b872c7e-6e0c-4a9d-9166-25058ad99e84.png)

**Comment by henilp105** [comment]
It seems that the md was mistyped ` **sqrt(x**2 + y**2)**` which would result into **sqrt(x**2 + y**2)**, thus the misprinting, Will escape the character for the sqroot  in the PR.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by henilp105** [comment]
Added Math jax to the site for mathematical expressions rendering.

**Comment by awvwgk** [comment]
I think we already have math rendering via sphinx, there is an extension for myst-markdown to enable it (`dollarmath`).

**Comment by henilp105** [comment]
@awvwgk should we shift to this type of packages :
![fortran_package](https://user-images.githubusercontent.com/37398093/185744232-24737946-bc64-4628-ba9b-5ce3f5335aa6.png)

**Comment by awvwgk** [comment]
This looks really good. This is a rubric directive?

We could also use [badges](https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html#badges) for the tags.

**Comment by awvwgk** [comment]
Also, can you check whether it looks better to have the release/version/... images directly below the header?

**Comment by henilp105** [comment]
> This is a rubric directive?

No sir, This is a styled div in myst.

> We could also use [badges](https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html#badges) for the tags.

I tried implementing it but then we won't be able to get the github data.

This is implementation of below the header , actually both look good , so, i am confused a bit.
 
![fortran_packages](https://user-images.githubusercontent.com/37398093/185747516-1aa03ffe-ecc9-46ce-b7d2-da76b582e5d6.png)

**Comment by awvwgk** [comment]
> I tried implementing it but then we won't be able to get the github data.

Maybe something like this could work?

```diff
-Tags: {{j.tags}}
+Tags: {% for tag in j.tags.split() %} {bdg-light}`{{ tag }}` {% endfor %}
```

**Comment by henilp105** [comment]
Thanks sir @awvwgk , This looks great.

![package](https://user-images.githubusercontent.com/37398093/185749491-c0b14b62-0714-4191-b3c7-64bd2e1988da.png)
