### ISSUE TITLE
Outdated information in docs

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#120]
I think we have a couple of outdated information in our documentation which still refers to the old jekyll page:

- *Icon packs* at https://fortran-lang.github.io/webpage/en/community/contributing/#icon-packs, should mention the MyST directives described at https://sphinx-design.readthedocs.io/en/sbt-theme/badges_buttons.html#inline-icons
- *Minibooks* at https://fortran-lang.github.io/webpage/en/community/minibooks/ does describe the old workflow

**Comment by henilp105** [comment]
@awvwgk sir should we optimise the yaml files ex. we aren't using the pages key of the learn section in yaml files ?

**Comment by henilp105** [comment]
Resolved both the issues will be patched in upcoming PR.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
