### ISSUE TITLE
Typo at the end of the homepage

### ISSUE THREAD

**Issue by vmagnin** [fortran-lang/webpage#143]
The last sentence of the homepage of Fortran-lang.org is ended by two dots:

> Or just write Fortran software for your research, business, or schoolwork. You can learn how to [get started here.](https://fortran-lang.org/en/learn/).

Although I don't know why because there is only one dot in the index.html file:
```
You can learn how to get started <a href="{{site.baseurl}}/learn/">here</a>.
```

**Comment by awvwgk** [comment]
I think you are looking at the wrong source. The main page is generated from https://github.com/fortran-lang/webpage/blob/main/source/index.md.

**Comment by vmagnin** [comment]
Thanks Sebastian.
I have just made a PR for this .md file.
