### ISSUE TITLE
Link broken in `Choosing a Compiler`

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/webpage#149]
"here" is supposed to link to the compiler section, but it is currently broken.

<img width="763" alt="Bildschirmfoto 2022-09-11 um 16 24 50" src="https://user-images.githubusercontent.com/43783196/189532737-304305dc-284f-4ba9-8882-2155c3b19c22.png">

**Comment by awvwgk** [comment]
Good catch, will be fixed with #150.
