### ISSUE TITLE
Run build workflow on pull requests?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#15]
Should we run the build workflow on every pull request? Other than the build preview we currently can only perform local checks whether the page actually builds. The build workflow doesn't need access to the repository secrets for the `API_TOKEN`, but only reads the cached data files.

While running the build workflow would not guarantee that the resulting page is correctly rendered, it would prevent any commits to break the sphinx build completely.

**Comment by henilp105** [comment]
Sir actually it isn't running on every PR, It has been made to check on every comment in PR for "#build preview or delete preview" comment. so if it does not find it then it cancels the run. as there had not been any other suitable way (in gh-actions) to check for the command in PR.

Thanks  and Regards,
Henil Shalin Panchal

**Comment by henilp105** [comment]
PR #24 resolves this. thus, I request this issue to be closed.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
