### ISSUE TITLE
Use full language name in language selector

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#172]
Currently only the language identifier is given in the language selection menu. It might be more intuitive to have the full name of the language there. The full name of the language should preferably be written in the actual language itself, to make it easier to find for native speakers. Not sure what the best way of sorting is in that case.

**Comment by henilp105** [comment]
@awvwgk Sir,it is surely possible but, The templates are not translate able thus we would have to put the translations in actual language manually in the template we wont be able to use the weblate.

**Comment by awvwgk** [comment]
Indeed, we would have to find the language name in the actual language, basically the same way as the language selection on [Wikipedia](https://en.wikipedia.org/wiki/Main_Page) works. A quick way to do this would be looking at the Wikipedia articles of the respective languages (*e.g.* [German](https://en.wikipedia.org/wiki/German_language), [Chinese](https://en.wikipedia.org/wiki/Chinese_language)). We can also ask the respective translators what the correct name is and insert it in the template.

**Comment by vmagnin** [comment]
It's OK for French = Français.

**Comment by aslozada** [comment]
Spanish = Español

**Comment by zoziha** [comment]
Simplified Chinese (zh-cn) = 简体中文
