### ISSUE TITLE
fortran_packages API_TOKEN bug

### ISSUE THREAD

**Issue by henilp105** [fortran-lang/webpage#18]
Sir, this is request you to please change the API_TOKEN value to **`username:GH_TOKEN`**  according to the new fortran_packages.py . 
As we are making **Authenticated GET** requests to **github api via https** thus we must use this format for authenticated requests.

https://github.com/fortran-lang/webpage/runs/7709341129?check_suite_focus=true

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
Fixed with https://github.com/fortran-lang/webpage/commit/2d45bd8f883ac25ec1be3142ab4dc39c056abdfd. Using now `token $API_TOKEN` for the header.

**Comment by henilp105** [comment]
https://github.com/fortran-lang/webpage/runs/7710875459?check_suite_focus=true 

Sir, this is request you to please change the API_TOKEN value `format` to **`username:GH_TOKEN`** according to the new fortran_packages.py .
As we are making Authenticated GET requests to github api via https thus we must use this format for authenticated requests.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
There was an issue with whitespace being escaped when part of a secret in GHA. The `API_TOKEN` secret now has to be only the token itself, it can be provided either with the `API_TOKEN` environment variable or the first command line argument to the script. The secret in `API_TOKEN` for this repo was upated accordingly.
