### ISSUE TITLE
GH-pages pr folder

### ISSUE THREAD

**Issue by henilp105** [fortran-lang/webpage#20]
Respected sir,
This is to request you to create a folder named `pr` in `gh-pages` branch to view the build output of the PRs.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
Can you add a step in the build preview workflow which will use `mkdir -p pr` to create the directory?

**Comment by henilp105** [comment]
sure. 
Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
