### ISSUE TITLE
The website is not being indexed by Bing

### ISSUE THREAD

**Issue by certik** [fortran-lang/webpage#266]
This is quite urgent. It has been many months and the website is not included in Bing.

This has been discussed at: https://fortran-lang.discourse.group/t/fortran-lang-no-longer-in-bing/4942, but so far we have not figured out how to fix it.

**Comment by awvwgk** [comment]
The sitemap we are currently uploading does not point to any existing pages since the language tag is appearing twice, see https://fortran-lang.org/sitemap.xml.

**Comment by henilp105** [comment]
Thanks @certik @awvwgk , Closing as Resolved.
