### ISSUE TITLE
button text translated removes all the button properties

### ISSUE THREAD

**Issue by henilp105** [fortran-lang/webpage#29]
@awvwgk Sir, as we add translation for text in buttons they lose their properties on the translated page. Most likely seems to be a bug of myst/sphinx. Example can be found on index page of de translation ("Get Started" button on index page). I have also been abel to reproduce this is various other buttons of like learn section in all the translations. How should we be able to resolve them ? 

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
I think https://github.com/executablebooks/sphinx-design/issues/44 is still an issue with sphinx-design. Didn't really get any input from upstream on this so far.

**Comment by awvwgk** [comment]
For the fpm docs we don't add translations to buttons for this reason, which is suboptimal. In the TOML Fortran documentation I avoided using buttons for this reason and just made the whole card clickable.

**Comment by awvwgk** [comment]
Alternative discussed today might be to create the button using ```:::{div}``` directive and manually add the classes.
