### ISSUE TITLE
Hosting of webpage

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#3]
Moving the discussion about hosting of the webpage to a separate thread. We are currently somewhat limited in what we can do due to using GH pages for hosting. For the playground project we also need to run a flask server, which can't be served by GH pages. We could make good use of a similar toolchain for the new webpage here.

cc @henilp105 @milancurcic @everythingfunctional @ashirrwad

**Comment by certik** [comment]
I very strongly recommend hosting the main website on github pages as usual, as a static website. That way the setup is robust, the hosting is very robust, it's fast, zero maintenance from us, etc.

Then, if we need a dedicated hosting for some subpage, I recommend hosting just that subpage somewhere, and we need to figure out how we are going to pay for it and how much it will cost and who will be responsible for maintaining it.

In addition to any dedicated hosting with docker I would also like to propose hosting LFortran, on static github pages, just like in the demo here: https://www.ubaidshaikh.me/lcompilers_frontend/. I think very soon we will be able to compile most codes, and it will be able to do what we want it to do.

**Comment by henilp105** [comment]
This Issue has been resolved by Implementing the **dirhtml** of sphinx and also implemented the old sitemap of jekyll site in PR #1.

Thanks and Regards,
Henil Shalin Panchal
