### ISSUE TITLE
Use markdown formatter for consistent style

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#43]
We could use a markdown formatter like [prettier](https://prettier.io/) to format all markdown files to get a more consistent overall usage of Markdown. Applying this as pre-commit hook would enable it to run on all changed files automatically. The disadvantage is of course a huge diff if applied for the first time.

Any opinions on this?

**Comment by zmoon** [comment]
Cool idea but does prettier handle MyST's extended Markdown?

**Comment by awvwgk** [comment]
We just discussed to do reformatting of the whole page with *prettier* to see whether any (MyST-)markdown usage is breaking by applying. In case we find we need special attention for MyST markdown, we can still investigate other solutions, mdformat-myst seems fine, we could write a pre-commit hook ourselves for it.

**Comment by zmoon** [comment]
> we could write a pre-commit hook ourselves for it

Upon investigation, looks like it could already be used [in this way](https://mdformat.readthedocs.io/en/stable/users/installation_and_usage.html#usage-as-a-pre-commit-hook). Though in my brief investigation it doesn't seem to do much for MyST-specific features.
