### ISSUE TITLE
Link to online compiler playground

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#44]
The Fortran-lang playground (https://github.com/fortran-lang/playground) should be linked from the webpage to make it easier to discover.

Possible options are:

- in the top navigation bar
- in the compiler section next to the supported compilers

cc @ashirrwad, @everythingfunctional

**Comment by henilp105** [comment]
@awvwgk @ashirrwad @milancurcic @everythingfunctional please feel free suggest the location for link.  The above 2 location seemed most apt during our conversation regarding link.

**Comment by milancurcic** [comment]
The top navbar or the Learn page seem appropriate to me to link to the playground from. The compilers page less so, at least until we can support more compilers (e.g. ifort, lfortran, flang) in the playground.

**Comment by henilp105** [comment]
Preview of this is available here : https://fortran-lang.github.io/webpage/pr/156  Thanks.

**Comment by everythingfunctional** [comment]
I'm of the opinion the Learn page is the most appropriate place for it, but I'm happy to have it in the Nav bar.

**Comment by awvwgk** [comment]
An alternative to the full label in the navbar could be an icon, next to the other external links, if we can find a meaningful icon which describes an online compiler playground in a single symbol.

**Comment by milancurcic** [comment]
Implemented by #156.
