### ISSUE TITLE
Incorrect layout for window width > 600 and < 720 pixels

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/webpage#6]
The new website looks great. Thanks for all the work.

For window width > 600 and < 720 pixels, the Join us section appears above the main section of the landing page. See the attached screenshot:
![Screenshot from 2022-08-05 13-46-24](https://user-images.githubusercontent.com/4133310/183132747-9b853a76-776d-4a6c-b080-235418b6829c.png)

**Comment by henilp105** [comment]
Thanks sir for review, I have patched (https://github.com/henilp105/webpage/commit/10876b7f199f3477906b5b8de9e32e0815022c6a) this bug in my repo and this issue will be resolved in the upcomming PR.

Thanks and Regards,
Henil Shalin Panchal

**Comment by henilp105** [comment]
PR #24 resolves this. thus, I request this issue to be closed.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
