### ISSUE TITLE
Have package, minibook and contributing guidelines as part of the webpage

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#7]
Should we move the packages, minibook, and/or contributing guidelines on the webpage rather than storing them in the repository?

The presentation on the webpage looks usually better and it would allow to localize those guidelines as well.

**Comment by henilp105** [comment]
Yes sir, It seems more apt and would be easy to locate for new members of the community. where should we keep this documentation like in the learn section or to make a separate section named Documentation  ?

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
The contributing guidelines could be in the community section. Same for the package and minibook guides.

**Comment by henilp105** [comment]
Thanks sir,  I will surely patch this.

Thanks and Regards,
Henil Shalin Panchal

**Comment by henilp105** [comment]
This has been patched , will be merged in the upcomming PR (https://github.com/henilp105/webpage/commit/6a04c49a92fca02960c9fa97aa1d7e1b0e15e999 ). 

Thanks and Regards,
Henil Shalin Panchal
