### ISSUE TITLE
Linting / Stylechecking of Python scripts

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/webpage#9]
We should include some basic style checking and linting for all Python scripts, I would suggest `black` for formatting and `pylint` for linting.

**Comment by henilp105** [comment]
should we add them as a part of gh-actions ? or only format the python scripts before commiting them to repo ? 

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
I have seen projects auto-apply those using precommit hooks. A GH action check to just run black and pylint might be sufficient for our purpose.

**Comment by zmoon** [comment]
Could add a pre-commit config and then use the pre-commit Action

**Comment by henilp105** [comment]
added a pre-commit config and a pre-commit hook thus would run before every commt.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by henilp105** [comment]
PR #24 resolves this. thus, I request this issue to be closed.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
